#### Initializing a Tensor

In [3]:
import torch

In [4]:
x = torch.tensor([[1,2]])
y = torch.tensor([[1], [2]])

In [5]:
print(x.shape)
print(y.shape)
print(x.dtype)

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [6]:
x = torch.tensor([False, 1, 0.7])
print(x)
print(x.shape)

tensor([0.0000, 1.0000, 0.7000])
torch.Size([3])


In [7]:
x = torch.tensor(["False", 1, 0.7])
print(x)
print(x.shape)

ValueError: too many dimensions 'str'

In [8]:
torch.zeros((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
torch.ones((3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
torch.zeros(size=(3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
torch.randint(low=0, high=10, size=(3,4))  # lower bound included, upper bound excluded

tensor([[1, 1, 2, 7],
        [6, 3, 3, 0],
        [7, 0, 5, 8]])

In [12]:
torch.rand((3,4)) # between 0 & 1

tensor([[0.9790, 0.2726, 0.0450, 0.5012],
        [0.6389, 0.6030, 0.9096, 0.7382],
        [0.5752, 0.5994, 0.8824, 0.4676]])

In [13]:
torch.randn((3,4)) # normally distributed numbers, between -1 & 1

tensor([[ 0.4192, -1.8743,  0.0311, -0.9565],
        [-0.7864,  0.4900, -1.5301, -0.3043],
        [-1.3214,  0.0734,  0.4199,  0.5251]])

In [14]:
import numpy as np

In [15]:
x = np.array([[2,3,4], [10,11,12]])
y = torch.tensor(x)

print(type(x))
print(type(y))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


#### Operations on Tensors

In [16]:
import torch

In [17]:
x = torch.tensor([[1,2,3,4],[5,6,7,8]])
print(x*10)

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])


In [18]:
x.add(10)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

In [19]:
y = torch.tensor([2,3,4,5])
print(y.shape)
y = y.view(4,1)
print(y.shape)
print(y)

torch.Size([4])
torch.Size([4, 1])
tensor([[2],
        [3],
        [4],
        [5]])


In [20]:
x = torch.randn((10,1,10))
print(x)
z1 = torch.squeeze(x, 1)
print(z1)

z2 = x.squeeze(1)
assert torch.all(z1==z2)
print(x.shape, z1.shape)

tensor([[[-0.9569,  0.8118, -1.4448,  1.4151, -0.2074, -0.5059, -0.7205,
          -0.5736,  0.7100,  0.0636]],

        [[-0.0659, -0.4090, -0.8585,  1.3653,  1.6447, -0.6566,  0.4956,
          -0.0283,  0.2407,  0.0425]],

        [[ 0.9198,  0.5420, -0.3498,  0.2010,  0.3164,  1.2394,  0.2895,
          -0.0942, -1.4311, -0.5424]],

        [[-0.3086, -0.7111, -0.4920,  0.4846, -1.0039,  0.9462, -0.2288,
           0.2405, -0.9831, -0.3875]],

        [[ 0.5329, -1.1401,  0.5782,  0.1699, -0.2152, -0.3838,  0.7671,
          -0.7716,  0.9008, -1.6718]],

        [[ 0.8047, -0.8498,  0.3100,  1.7706, -0.1315, -0.7646, -1.1975,
           0.3807,  0.2568,  0.6318]],

        [[-0.6992, -1.2429,  0.6605,  0.6097, -1.6128, -0.8537,  1.2419,
          -0.3081, -2.9070, -0.5758]],

        [[ 0.5066, -0.0843, -0.0620, -2.1819, -1.5052, -0.3564,  0.5944,
           1.5779,  0.9903,  2.0691]],

        [[ 0.3296, -1.4374, -1.6857, -0.5798,  1.7416,  1.3908,  1.3229,
          -0.6923, -0.5

In [21]:
x = torch.randn(10, 10)
print(x)
print(x.shape)

z1 =x.unsqueeze(0)
print(z1)
print(z1.shape)

tensor([[-2.1998,  0.8427, -0.0916,  0.6376,  1.4570,  0.6475, -1.2181, -2.1515,
          1.2546,  1.9838],
        [-0.5322, -1.0507, -0.6577,  0.7203, -0.5148, -0.3638,  0.0942, -1.0700,
          0.6047,  1.5723],
        [-0.6404, -0.1651, -1.1510,  0.9489,  0.2869, -1.3953, -0.3186, -0.5372,
         -1.4304, -0.7250],
        [ 0.6236,  0.5986,  0.1607, -0.4379, -0.5186, -1.0470, -0.8036,  1.3833,
          0.5327,  0.2956],
        [-0.4134,  0.1011,  0.1325, -0.3788,  1.0174, -0.0586, -0.4624, -0.1278,
         -1.6397, -0.3639],
        [ 0.7853,  1.3229,  1.5025,  0.3761,  0.3418, -1.4026, -0.9945, -0.6952,
         -0.5556, -0.8807],
        [-0.5571,  0.3504, -0.4570, -0.5181, -0.8573,  0.7346,  0.4262,  1.2429,
          0.1984, -1.8276],
        [-0.3069,  0.7488,  1.3397,  1.0375, -2.3818,  1.2057,  0.2114, -0.3425,
          0.3827, -0.5128],
        [ 1.3330, -1.7878,  0.5816,  0.5057, -0.4341, -1.3130, -0.7046, -0.3280,
         -1.8560, -0.8073],
        [-0.8561,  

In [22]:
x = torch.randn(10, 10)
z2, z3, z4 = x[None], x[:, None], x[:,:, None]
print(z2, z2.shape)
print(z3, z3.shape)
print(z4, z4.shape)

tensor([[[-1.1145,  1.9003, -1.2124,  1.3895, -1.0832,  0.3612, -0.7083,
           0.5020, -0.8739, -0.4982],
         [-0.2180,  0.0969,  0.7310,  0.5332, -0.0790, -1.2330,  0.7953,
           0.4355, -0.9343, -0.1618],
         [-1.6888, -1.8357,  0.0431,  0.1293, -0.7128, -0.2879, -0.6345,
          -0.9808,  0.6669,  0.0367],
         [ 0.1416, -0.7521,  1.3703,  1.2858, -0.6126, -1.7437, -0.2972,
          -0.7479,  0.9300,  1.2347],
         [ 1.0448, -1.4798,  0.6154, -1.0695,  0.6599,  0.0235, -0.6991,
           0.9122,  0.5468,  0.0898],
         [ 0.5495,  0.0888,  0.9761,  0.9377,  0.2821,  0.1615,  1.5334,
           0.4727,  0.7915,  0.0041],
         [ 3.1654, -0.8545, -0.5882,  0.7844,  0.7389,  0.1965,  0.0689,
          -0.3003,  1.1652,  0.6523],
         [ 1.2521,  0.7299,  1.0986, -1.9935, -2.0724, -1.0439, -0.3925,
          -2.0981,  0.3869, -0.2563],
         [ 0.5564, -0.7878, -0.9874,  0.2490, -1.7184, -1.1361, -0.6169,
          -0.9335,  1.7256, -2.2497],
 

In [23]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
print(x, x.shape)
print(y, y.shape)
print(torch.matmul(x,y))

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]]) torch.Size([2, 4])
tensor([[2],
        [3],
        [4],
        [5]]) torch.Size([4, 1])
tensor([[40],
        [96]])


In [24]:
print(x@y)

tensor([[40],
        [96]])


In [25]:
x = torch.randn(10,10,10)
z = torch.cat([x,x], axis=0)
print('Cat axis 0:', x.shape, z.shape)


z = torch.cat([x,x], axis=1)
print('Cat axis 1:', x.shape, z.shape)

Cat axis 0: torch.Size([10, 10, 10]) torch.Size([20, 10, 10])
Cat axis 1: torch.Size([10, 10, 10]) torch.Size([10, 20, 10])


In [26]:
x = torch.arange(25).reshape(5,5)
print(x, x.shape, x.max())

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]) torch.Size([5, 5]) tensor(24)


In [27]:
x.max(dim=0)

torch.return_types.max(
values=tensor([20, 21, 22, 23, 24]),
indices=tensor([4, 4, 4, 4, 4]))

In [28]:
x.max(dim=1)

torch.return_types.max(
values=tensor([ 4,  9, 14, 19, 24]),
indices=tensor([4, 4, 4, 4, 4]))

In [29]:
x = torch.randn(10, 20, 30)
z = x.permute(2, 0, 1)
print(x.shape, z.shape)

torch.Size([10, 20, 30]) torch.Size([30, 10, 20])


#### Auto Gradients of Tensor Objects

In [30]:
import torch

In [31]:
x = torch.tensor([[2.,-1.],[1.,1.]], requires_grad=True)
print(x)

tensor([[ 2., -1.],
        [ 1.,  1.]], requires_grad=True)


In [32]:
type(x)

torch.Tensor

In [33]:
out = x.pow(2).sum()
print(out)

tensor(7., grad_fn=<SumBackward0>)


In [34]:
out.backward()

In [35]:
x.grad

tensor([[ 4., -2.],
        [ 2.,  2.]])

#### Numpy vs Pytorch

In [55]:
import torch

In [56]:
x = torch.rand(1, 6400)
y = torch.rand(6400, 5000)

In [57]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [58]:
x, y = x.to(device), y.to(device)

In [60]:
%timeit z = x@y

1.34 ms ± 1.64 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [61]:
x, y = x.cpu(), y.cpu()
%timeit z = x@y

5.94 ms ± 110 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [62]:
import numpy as np
x = np.random.random((1, 6400))
y = np.random.random((6400, 5000))
%timeit z = np.matmul(x,y)

10.5 ms ± 253 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
